extends:
    - eslint:recommended
    - google
plugins:
    - vue
env:
    browser: true
    es6: true
    commonjs: true
parserOptions:
    sourceType: module
    ecmaVersion: 6
    ecmaFeatures:
        experimentalObjectRestSpread: true
rules:
    semi: ["error", "always"]
    no-console: ["error", { "allow": ["warn", "error"] }]
globals:
    WEBPACK_APP_VERSION: true
    WEBPACK_TIMESTAMP: true
